language: java

jdk:
  - oraclejdk10

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -f $TRAVIS_BUILD_DIR/server/core/src/main/resources/create_schema.sql -U postgres

script:
  - mvn clean test
